# Generated by Django 2.1.7 on 2019-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='goal',
            field=models.IntegerField(null=True),
        ),
    ]
